import = [
    "~/.config/alacritty/themes/hyper.toml"
]

[window]
padding.x = 10
padding.y = 40
opacity = 0.2
blur = true
option_as_alt = "Both"
decorations = "Transparent"

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 19